spring:
  config:
    activate:
      on-profile: prod

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:2}
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

app:
  session:
    default-duration-minutes: ${APP_SESSION_DURATION:60}
  cpf-validator:
    enabled: ${CPF_VALIDATOR_ENABLED:true}

logging:
  level:
    com.ppfurtado.desafiovotacao: WARN
    org.springframework.web: WARN
    org.hibernate: WARN